# Generated by Django 5.2.3 on 2025-06-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BruteData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id_route', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='traffic', serialize=False, to='main.brutedata')),
                ('percent_VL', models.FloatField()),
                ('TJM', models.FloatField()),
                ('percent_PL', models.FloatField()),
                ('TJM_7d', models.IntegerField()),
                ('TJM_5d', models.IntegerField()),
                ('max_traffic', models.IntegerField()),
                ('min_traffic', models.IntegerField()),
                ('VL', models.FloatField()),
                ('PL', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField()),
                ('trimestre', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('brute_data', models.ManyToManyField(related_name='campagnes', to='main.brutedata')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('num_section', models.AutoField(primary_key=True, serialize=False)),
                ('lieu_d', models.CharField(max_length=255)),
                ('lieu_f', models.CharField(max_length=255)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.commune')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.route')),
            ],
        ),
        migrations.AddField(
            model_name='brutedata',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brute_data', to='main.section'),
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='main.wilaya'),
        ),
    ]
