# Generated by Django 5.2.3 on 2025-06-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.IntegerField(blank=True, choices=[(1, '01'), (2, '02')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='id_route',
        ),
        migrations.RemoveField(
            model_name='section',
            name='num_section',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='TJM',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='max_traffic',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='min_traffic',
        ),
        migrations.AddField(
            model_name='route',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='traffic',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='trafic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brutedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brutedata',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brute_data', to='main.section'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='brute_data',
            field=models.ManyToManyField(blank=True, related_name='campagnes', to='main.brutedata'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='trimestre',
            field=models.IntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='main.wilaya'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.commune'),
        ),
        migrations.AlterField(
            model_name='section',
            name='lieu_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='lieu_f',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.route'),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='PL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='TJM_5d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='TJM_7d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='VL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='percent_PL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='percent_VL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
