# Generated by Django 5.2.3 on 2025-06-20 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sens_remove_route_id_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='brutedata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic', to='main.brutedata'),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
